// Code generated by ogen, DO NOT EDIT.

package api

import (
	"net/http"

	"github.com/go-faster/errors"
	"github.com/go-faster/jx"
	"go.opentelemetry.io/otel/codes"
	"go.opentelemetry.io/otel/trace"

	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/uri"
)

func encodeDeleteAPIV1NoteResponse(response DeleteAPIV1NoteRes, w http.ResponseWriter, span trace.Span) error {
	switch response := response.(type) {
	case *DeleteAPIV1NoteOK:
		w.WriteHeader(200)
		span.SetStatus(codes.Ok, http.StatusText(200))

		return nil

	case *DeleteAPIV1NoteBadRequest:
		w.WriteHeader(400)
		span.SetStatus(codes.Error, http.StatusText(400))

		return nil

	default:
		return errors.Errorf("unexpected response type: %T", response)
	}
}

func encodeDeleteAPIV1UserResponse(response DeleteAPIV1UserRes, w http.ResponseWriter, span trace.Span) error {
	switch response := response.(type) {
	case *DeleteAPIV1UserOK:
		w.WriteHeader(200)
		span.SetStatus(codes.Ok, http.StatusText(200))

		return nil

	case *DeleteAPIV1UserBadRequest:
		w.WriteHeader(400)
		span.SetStatus(codes.Error, http.StatusText(400))

		return nil

	default:
		return errors.Errorf("unexpected response type: %T", response)
	}
}

func encodeGetAPIV1NoteResponse(response GetAPIV1NoteRes, w http.ResponseWriter, span trace.Span) error {
	switch response := response.(type) {
	case *NoteHeaders:
		w.Header().Set("Content-Type", "application/json; charset=utf-8")
		// Encoding response headers.
		{
			h := uri.NewHeaderEncoder(w.Header())
			// Encode "Access-Control-Allow-Headers" header.
			{
				cfg := uri.HeaderParameterEncodingConfig{
					Name:    "Access-Control-Allow-Headers",
					Explode: false,
				}
				if err := h.EncodeParam(cfg, func(e uri.Encoder) error {
					if val, ok := response.AccessControlAllowHeaders.Get(); ok {
						return e.EncodeValue(conv.StringToString(val))
					}
					return nil
				}); err != nil {
					return errors.Wrap(err, "encode Access-Control-Allow-Headers header")
				}
			}
			// Encode "Access-Control-Allow-Methods" header.
			{
				cfg := uri.HeaderParameterEncodingConfig{
					Name:    "Access-Control-Allow-Methods",
					Explode: false,
				}
				if err := h.EncodeParam(cfg, func(e uri.Encoder) error {
					if val, ok := response.AccessControlAllowMethods.Get(); ok {
						return e.EncodeValue(conv.StringToString(val))
					}
					return nil
				}); err != nil {
					return errors.Wrap(err, "encode Access-Control-Allow-Methods header")
				}
			}
			// Encode "Access-Control-Allow-Origin" header.
			{
				cfg := uri.HeaderParameterEncodingConfig{
					Name:    "Access-Control-Allow-Origin",
					Explode: false,
				}
				if err := h.EncodeParam(cfg, func(e uri.Encoder) error {
					if val, ok := response.AccessControlAllowOrigin.Get(); ok {
						return e.EncodeValue(conv.StringToString(val))
					}
					return nil
				}); err != nil {
					return errors.Wrap(err, "encode Access-Control-Allow-Origin header")
				}
			}
		}
		w.WriteHeader(200)
		span.SetStatus(codes.Ok, http.StatusText(200))

		e := new(jx.Encoder)
		response.Response.Encode(e)
		if _, err := e.WriteTo(w); err != nil {
			return errors.Wrap(err, "write")
		}

		return nil

	case *GetAPIV1NoteBadRequest:
		w.WriteHeader(400)
		span.SetStatus(codes.Error, http.StatusText(400))

		return nil

	default:
		return errors.Errorf("unexpected response type: %T", response)
	}
}

func encodeGetAPIV1UserResponse(response GetAPIV1UserRes, w http.ResponseWriter, span trace.Span) error {
	switch response := response.(type) {
	case *User:
		w.Header().Set("Content-Type", "application/json; charset=utf-8")
		w.WriteHeader(200)
		span.SetStatus(codes.Ok, http.StatusText(200))

		e := new(jx.Encoder)
		response.Encode(e)
		if _, err := e.WriteTo(w); err != nil {
			return errors.Wrap(err, "write")
		}

		return nil

	case *GetAPIV1UserBadRequest:
		w.WriteHeader(400)
		span.SetStatus(codes.Error, http.StatusText(400))

		return nil

	default:
		return errors.Errorf("unexpected response type: %T", response)
	}
}

func encodeListAPIV1NoteResponse(response ListAPIV1NoteRes, w http.ResponseWriter, span trace.Span) error {
	switch response := response.(type) {
	case *ListAPIV1NoteOK:
		w.WriteHeader(200)
		span.SetStatus(codes.Ok, http.StatusText(200))

		return nil

	case *ListAPIV1NoteBadRequest:
		w.WriteHeader(400)
		span.SetStatus(codes.Error, http.StatusText(400))

		return nil

	default:
		return errors.Errorf("unexpected response type: %T", response)
	}
}

func encodePostAPIV1NoteResponse(response PostAPIV1NoteRes, w http.ResponseWriter, span trace.Span) error {
	switch response := response.(type) {
	case *PostAPIV1NoteOK:
		w.WriteHeader(200)
		span.SetStatus(codes.Ok, http.StatusText(200))

		return nil

	case *PostAPIV1NoteBadRequest:
		w.WriteHeader(400)
		span.SetStatus(codes.Error, http.StatusText(400))

		return nil

	default:
		return errors.Errorf("unexpected response type: %T", response)
	}
}

func encodePostAPIV1UserResponse(response PostAPIV1UserRes, w http.ResponseWriter, span trace.Span) error {
	switch response := response.(type) {
	case *PostAPIV1UserOK:
		w.WriteHeader(200)
		span.SetStatus(codes.Ok, http.StatusText(200))

		return nil

	case *PostAPIV1UserBadRequest:
		w.WriteHeader(400)
		span.SetStatus(codes.Error, http.StatusText(400))

		return nil

	default:
		return errors.Errorf("unexpected response type: %T", response)
	}
}

func encodePutAPIV1NoteResponse(response PutAPIV1NoteRes, w http.ResponseWriter, span trace.Span) error {
	switch response := response.(type) {
	case *PutAPIV1NoteOK:
		w.WriteHeader(200)
		span.SetStatus(codes.Ok, http.StatusText(200))

		return nil

	case *PutAPIV1NoteBadRequest:
		w.WriteHeader(400)
		span.SetStatus(codes.Error, http.StatusText(400))

		return nil

	default:
		return errors.Errorf("unexpected response type: %T", response)
	}
}

func encodePutAPIV1UserResponse(response PutAPIV1UserRes, w http.ResponseWriter, span trace.Span) error {
	switch response := response.(type) {
	case *PutAPIV1UserOK:
		w.WriteHeader(200)
		span.SetStatus(codes.Ok, http.StatusText(200))

		return nil

	case *PutAPIV1UserBadRequest:
		w.WriteHeader(400)
		span.SetStatus(codes.Error, http.StatusText(400))

		return nil

	default:
		return errors.Errorf("unexpected response type: %T", response)
	}
}
