// Code generated by ogen, DO NOT EDIT.
package api

type ConflictAPIV1Res interface {
	conflictAPIV1Res()
}

type DeleteAPIV1NoteRes interface {
	deleteAPIV1NoteRes()
}

type DeleteAPIV1UserRes interface {
	deleteAPIV1UserRes()
}

type GetAPIV1NoteRes interface {
	getAPIV1NoteRes()
}

type GetAPIV1UserRes interface {
	getAPIV1UserRes()
}

type ListAPIV1NoteRes interface {
	listAPIV1NoteRes()
}

type PostAPIV1NoteRes interface {
	postAPIV1NoteRes()
}

type PostAPIV1UserRes interface {
	postAPIV1UserRes()
}

type PutAPIV1NoteRes interface {
	putAPIV1NoteRes()
}

type PutAPIV1UserRes interface {
	putAPIV1UserRes()
}
