openapi: 3.1.0
x-stoplight:
  id: ll4cmuu17js47
info:
  title: CalenGo
  version: '1.0'
servers: []
paths:
  '/api/v1/note/{note}':
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Note'
        '400':
          description: Bad Request
      operationId: get-api-v1-note
      x-stoplight:
        id: gm4ucylb4nhnn
      x-internal: false
      parameters:
        - name: note
          schema:
            type: string
          in: path
          required: true
        - schema:
            type: string
          in: cookie
          required: true
          name: credentials
          description: 'username:password'
          deprecated: false
  /api/v1/note:
    post:
      summary: Your POST endpoint
      tags: []
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
      operationId: post-api-v1-note
      x-stoplight:
        id: q7ajxt7zp0hkd
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Note'
      parameters:
        - schema:
            type: string
          in: cookie
          required: true
          name: credentials
          description: 'username:password'
          deprecated: false
    put:
      summary: Your POST endpoint
      tags: []
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
      operationId: put-api-v1-note
      x-stoplight:
        id: w5w7deyffsusv
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Note'
      parameters:
        - schema:
            type: string
          in: cookie
          required: true
          name: credentials
          description: 'username:password'
          deprecated: false
    delete:
      summary: Your POST endpoint
      tags: []
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
      operationId: delete-api-v1-note
      x-stoplight:
        id: 7tcrrpw4gehv2
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Note'
      parameters:
        - schema:
            type: string
          in: cookie
          required: true
          name: credentials
          description: 'username:password'
          deprecated: false
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Note'
                  x-stoplight:
                    id: 3tyzm4ja1x5ul
        '400':
          description: Bad Request
      operationId: list-api-v1-note
      x-stoplight:
        id: gbz745ic1txj2
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - startTime
                - endTime
              properties:
                startTime:
                  type: string
                  x-stoplight:
                    id: gxm9wi5mwv97r
                endTime:
                  type: string
                  x-stoplight:
                    id: j2zxbkozp1dvt
      parameters:
        - schema:
            type: string
          in: cookie
          required: true
          name: credentials
          description: 'username:password'
          deprecated: false
  '/api/v1/user/{user}':
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Bad Request
      operationId: get-api-v1-user
      x-stoplight:
        id: 4krcrn1o5mopx
      x-internal: false
      parameters:
        - name: user
          schema:
            type: string
          in: path
          required: true
        - schema:
            type: string
          in: cookie
          required: true
          name: credentials
          description: 'username:password'
          deprecated: false
  /api/v1/user:
    post:
      summary: Your POST endpoint
      tags: []
      responses:
        '200':
          description: OK
          headers:
            Set-Cookie:
              schema:
                type: string
                example: 'credentials=user:pass; Path=/; HttpOnly'
        '400':
          description: Bad Request
      operationId: post-api-v1-user
      x-stoplight:
        id: exgfsx5vijha0
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      parameters: []
    put:
      summary: Your POST endpoint
      tags: []
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
      operationId: put-api-v1-user
      x-stoplight:
        id: qsiq8gsaobkzf
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      parameters:
        - schema:
            type: string
          in: cookie
          required: true
          name: credentials
          description: 'username:password'
          deprecated: false
    delete:
      summary: Your POST endpoint
      tags: []
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
      operationId: delete-api-v1-user
      x-stoplight:
        id: cr47izhwwy6u0
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      parameters:
        - schema:
            type: string
          in: cookie
          required: true
          name: credentials
          description: 'username:password'
          deprecated: false
components:
  schemas:
    User:
      title: User
      type: object
      x-stoplight:
        id: 16tdk57ybrz0j
      required:
        - name
        - password
      properties:
        name:
          type: string
          x-stoplight:
            id: a684mzf3o3r7v
          x-oapi-codegen-extra-tags:
            db: name
        password:
          type: string
          x-stoplight:
            id: x1zjmrpr4uu49
          x-oapi-codegen-extra-tags:
            db: password
    Note:
      title: Note
      x-stoplight:
        id: sdtgqvkw44qm9
      type: object
      required:
        - name
        - description
        - startTime
        - endTime
      properties:
        name:
          type: string
          x-stoplight:
            id: tcr9iwep1csvp
          x-oapi-codegen-extra-tags:
            db: name
        description:
          type: string
          x-stoplight:
            id: evf0kjbsxkoqa
          x-oapi-codegen-extra-tags:
            db: description
        startTime:
          type: string
          x-stoplight:
            id: brlnqtqete4fc
          x-oapi-codegen-extra-tags:
            db: start_time
        endTime:
          type: string
          x-stoplight:
            id: 4u84jox7hpyws
          x-oapi-codegen-extra-tags:
            db: end_time
