openapi: 3.1.0
x-stoplight:
  id: s21ydxptoex9m
info:
  title: CalenGo
  version: '1.0'
servers: []
paths:
  '/api/v1/note/{note}':
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Note'
        '400':
          description: Bad Request
      operationId: get-api-v1-note
      x-stoplight:
        id: fa6zd7fjrs35m
      x-internal: false
      parameters:
        - name: note
          schema:
            type: string
          in: path
          required: true
  /api/v1/note:
    post:
      summary: Your POST endpoint
      tags: []
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
      operationId: post-api-v1-note
      x-stoplight:
        id: ynbna4m3bi2ma
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Note'
      parameters: []
    put:
      summary: Your POST endpoint
      tags: []
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
      operationId: put-api-v1-note
      x-stoplight:
        id: egzqo8q5setts
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Note'
      parameters: []
    delete:
      summary: Your POST endpoint
      tags: []
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
      operationId: delete-api-v1-note
      x-stoplight:
        id: 0gjmql7d2htgc
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Note'
      parameters: []
    patch:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Note'
                  x-stoplight:
                    id: mvxdfpzo8892p
        '400':
          description: Bad Request
      operationId: list-api-v1-note
      x-stoplight:
        id: azrvdqq6c9xqd
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - startTime
                - endTime
              properties:
                startTime:
                  type: string
                  x-stoplight:
                    id: vb158gbmhn66d
                endTime:
                  type: string
                  x-stoplight:
                    id: em4tjjewrzmkf
      parameters: []
  '/api/v1/user/{user}':
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Bad Request
      operationId: get-api-v1-user
      x-stoplight:
        id: 7fflcqjammzag
      x-internal: false
      parameters:
        - name: user
          schema:
            type: string
          in: path
          required: true
  /api/v1/user:
    post:
      summary: Your POST endpoint
      tags: []
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
      operationId: post-api-v1-user
      x-stoplight:
        id: z7nplxqgdtelp
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      parameters: []
    put:
      summary: Your POST endpoint
      tags: []
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
      operationId: put-api-v1-user
      x-stoplight:
        id: v84uzylocjaxp
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      parameters: []
    delete:
      summary: Your POST endpoint
      tags: []
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
      operationId: delete-api-v1-user
      x-stoplight:
        id: bbvig2ftzq81y
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      parameters: []
components:
  schemas:
    User:
      title: User
      type: object
      x-stoplight:
        id: swrwx81j2i2o2
      required:
        - name
        - password
      properties:
        name:
          type: string
          x-stoplight:
            id: s72fdbxfzcob4
          x-oapi-codegen-extra-tags:
            db: name
        password:
          type: string
          x-stoplight:
            id: f8l8xaitkxw2u
          x-oapi-codegen-extra-tags:
            db: password
    Note:
      title: Note
      x-stoplight:
        id: 7z9wkzkhwm467
      type: object
      required:
        - name
        - description
        - startTime
        - endTime
      properties:
        name:
          type: string
          x-stoplight:
            id: uprfucq6w3d3v
          x-oapi-codegen-extra-tags:
            db: name
        description:
          type: string
          x-stoplight:
            id: k06q27mrrcruz
          x-oapi-codegen-extra-tags:
            db: description
        startTime:
          type: string
          x-stoplight:
            id: tsmuwhlqpsmwm
          x-oapi-codegen-extra-tags:
            db: start_time
        endTime:
          type: string
          x-stoplight:
            id: dbtjlgmp2stud
          x-oapi-codegen-extra-tags:
            db: end_time
