/**
 * CalenGo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Note from './Note';

/**
 * The ConflictApiV1200ResponseInner model module.
 * @module model/ConflictApiV1200ResponseInner
 * @version 1.0
 */
class ConflictApiV1200ResponseInner {
    /**
     * Constructs a new <code>ConflictApiV1200ResponseInner</code>.
     * @alias module:model/ConflictApiV1200ResponseInner
     * @param first {module:model/Note} 
     * @param second {module:model/Note} 
     */
    constructor(first, second) { 
        
        ConflictApiV1200ResponseInner.initialize(this, first, second);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, first, second) { 
        obj['first'] = first;
        obj['second'] = second;
    }

    /**
     * Constructs a <code>ConflictApiV1200ResponseInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ConflictApiV1200ResponseInner} obj Optional instance to populate.
     * @return {module:model/ConflictApiV1200ResponseInner} The populated <code>ConflictApiV1200ResponseInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ConflictApiV1200ResponseInner();

            if (data.hasOwnProperty('first')) {
                obj['first'] = Note.constructFromObject(data['first']);
            }
            if (data.hasOwnProperty('second')) {
                obj['second'] = Note.constructFromObject(data['second']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ConflictApiV1200ResponseInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ConflictApiV1200ResponseInner</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ConflictApiV1200ResponseInner.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // validate the optional field `first`
        if (data['first']) { // data not null
          Note.validateJSON(data['first']);
        }
        // validate the optional field `second`
        if (data['second']) { // data not null
          Note.validateJSON(data['second']);
        }

        return true;
    }


}

ConflictApiV1200ResponseInner.RequiredProperties = ["first", "second"];

/**
 * @member {module:model/Note} first
 */
ConflictApiV1200ResponseInner.prototype['first'] = undefined;

/**
 * @member {module:model/Note} second
 */
ConflictApiV1200ResponseInner.prototype['second'] = undefined;






export default ConflictApiV1200ResponseInner;

