/**
 * CalenGo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ListApiV1NoteRequest model module.
 * @module model/ListApiV1NoteRequest
 * @version 1.0
 */
class ListApiV1NoteRequest {
    /**
     * Constructs a new <code>ListApiV1NoteRequest</code>.
     * @alias module:model/ListApiV1NoteRequest
     * @param startTime {String} 
     * @param endTime {String} 
     */
    constructor(startTime, endTime) { 
        
        ListApiV1NoteRequest.initialize(this, startTime, endTime);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, startTime, endTime) { 
        obj['startTime'] = startTime;
        obj['endTime'] = endTime;
    }

    /**
     * Constructs a <code>ListApiV1NoteRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ListApiV1NoteRequest} obj Optional instance to populate.
     * @return {module:model/ListApiV1NoteRequest} The populated <code>ListApiV1NoteRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ListApiV1NoteRequest();

            if (data.hasOwnProperty('startTime')) {
                obj['startTime'] = ApiClient.convertToType(data['startTime'], 'String');
            }
            if (data.hasOwnProperty('endTime')) {
                obj['endTime'] = ApiClient.convertToType(data['endTime'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ListApiV1NoteRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ListApiV1NoteRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ListApiV1NoteRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['startTime'] && !(typeof data['startTime'] === 'string' || data['startTime'] instanceof String)) {
            throw new Error("Expected the field `startTime` to be a primitive type in the JSON string but got " + data['startTime']);
        }
        // ensure the json data is a string
        if (data['endTime'] && !(typeof data['endTime'] === 'string' || data['endTime'] instanceof String)) {
            throw new Error("Expected the field `endTime` to be a primitive type in the JSON string but got " + data['endTime']);
        }

        return true;
    }


}

ListApiV1NoteRequest.RequiredProperties = ["startTime", "endTime"];

/**
 * @member {String} startTime
 */
ListApiV1NoteRequest.prototype['startTime'] = undefined;

/**
 * @member {String} endTime
 */
ListApiV1NoteRequest.prototype['endTime'] = undefined;






export default ListApiV1NoteRequest;

